version: '3'
services:
  dev:
    build: .
    image: neolol-fe-dev:latest
    working_dir: /usr/src/app
    environment:
      - API_URL=https://api.dev.qa.neolol.com
    command: bash -c "npm run build && npm run development"
    ports:
      - 3002:3002
