version: '3'
services:
  staging:
    build: .
    image: neolol-fe-staging:latest
    working_dir: /usr/src/app
    environment:
      - API_URL=https://api.dev.staging.neolol.com
    command: bash -c "npm run build && npm run staging"
    ports:
      - 3001:3001
